from __future__ import annotations

from collections.abc import Mapping

from marktex.backend.lualatex.bibliography import LuaLaTeXBibliography, bibliography_summary
from marktex.core import (
    Citation,
    CodeBlock,
    CodeExpression,
    CodeText,
    Conditional,
    Document,
    DocumentPatch,
    Emphasis,
    FootnoteDefinition,
    FootnoteRef,
    Heading,
    Image,
    InlineCode,
    InlineExpression,
    Link,
    Paragraph,
    Strong,
    Table,
    Text,
)
from marktex.core import object_to_json
from marktex.host.python.symbolic import SymbolicExpr, SymbolicValue
from marktex.mos import CallUnit, RawString
from marktex.source import MarkTeXError, SourceSpan


def make_backend_ir(document: Document) -> dict[str, object]:
    return {
        "target": "lualatex",
        "events": [object_to_json(event) for event in document.events],
        "blocks": [object_to_json(block) for block in document.blocks],
        "bibliography": bibliography_summary(document),
    }


def emit_lualatex(document: Document) -> str:
    return LuaLaTeXEmitter(document).emit()


class LuaLaTeXEmitter:
    def __init__(self, document: Document) -> None:
        self.document = document
        self.footnotes: Mapping[str, FootnoteDefinition] = {
            footnote.label: footnote for footnote in document.footnotes
        }
        self.bibliography = LuaLaTeXBibliography(document, escape_latex, escape_url)

    def emit(self) -> str:
        geometry_options = layout_options(self.document)
        preamble = [
            "% Generated by MarkTeX V0. Target: lualatex.",
            r"\documentclass{article}",
            r"\usepackage{fontspec}",
            r"\usepackage{luatexja}",
            r"\usepackage{hyperref}",
            r"\usepackage{array}",
            r"\usepackage{lastpage}",
            r"\usepackage{graphicx}",
            r"\usepackage{refcount}",
        ]
        if geometry_options:
            preamble.append(r"\usepackage[" + ",".join(geometry_options) + r"]{geometry}")
        else:
            preamble.append(r"\usepackage{geometry}")
        preamble.extend(["", r"\begin{document}"])

        body: list[str] = []
        for block in self.document.blocks:
            body.extend(self.emit_block(block))
            body.append("")
        references = self.bibliography.reference_lines()
        if references:
            body.extend(references)
            body.append("")

        return "\n".join(preamble + body + [r"\end{document}", ""])

    def emit_block(self, block: object) -> list[str]:
        if isinstance(block, Paragraph):
            return [self.emit_inline_children(block.children)]
        if isinstance(block, Heading):
            return [self.heading_command(block.level, block.children)]
        if isinstance(block, CodeBlock):
            return self.emit_code_block(block)
        if isinstance(block, Table):
            return self.emit_table(block)
        if isinstance(block, Conditional):
            return self.emit_conditional(block)
        raise MarkTeXError(f"unsupported block for LuaLaTeX backend: {block!r}")

    def heading_command(self, level: int, children: tuple[object, ...]) -> str:
        command = {
            1: "section",
            2: "subsection",
            3: "subsubsection",
            4: "paragraph",
            5: "subparagraph",
            6: "subparagraph",
        }.get(level, "paragraph")
        return "\\" + command + "{" + self.emit_inline_children(children) + "}"

    def emit_code_block(self, block: CodeBlock) -> list[str]:
        if not block.interpolated or not block.parts:
            return [r"\begin{verbatim}", block.body.rstrip("\n"), r"\end{verbatim}"]
        body = "".join(self.emit_code_part(part) for part in block.parts).rstrip("\n")
        return [
            r"\par\noindent\begingroup",
            r"\ttfamily\obeyspaces\obeylines",
            body,
            r"\par\endgroup",
        ]

    def emit_code_part(self, part: object) -> str:
        if isinstance(part, CodeText):
            return escape_plain_latex(part.value)
        if isinstance(part, CodeExpression):
            return expression_value_to_lualatex(part.value, part.source, part.origin)
        raise MarkTeXError(f"unsupported code part for LuaLaTeX backend: {part!r}")

    def emit_table(self, table: Table) -> list[str]:
        column_count = len(table.header)
        spec = "|".join(["l"] * column_count)
        deferred_footnotes: list[str] = []
        lines = [r"\begin{tabular}{" + spec + "}"]
        lines.append(self.emit_table_row(table.header, deferred_footnotes))
        lines.append(r"\hline")
        for row in table.rows:
            lines.append(self.emit_table_row(row, deferred_footnotes))
        lines.append(r"\end{tabular}")
        if deferred_footnotes:
            lines.append(r"\addtocounter{footnote}{-" + str(len(deferred_footnotes)) + "}")
            lines.extend(
                r"\stepcounter{footnote}\footnotetext{" + footnote + "}"
                for footnote in deferred_footnotes
            )
        return lines

    def emit_table_row(
        self,
        row: tuple[tuple[object, ...], ...],
        deferred_footnotes: list[str],
    ) -> str:
        return (
            " & ".join(
                self.emit_inline_children(
                    cell,
                    context="table_cell",
                    deferred_footnotes=deferred_footnotes,
                )
                for cell in row
            )
            + r" \\"
        )

    def emit_inline_children(
        self,
        children: tuple[object, ...],
        *,
        context: str = "normal",
        deferred_footnotes: list[str] | None = None,
    ) -> str:
        return "".join(
            self.emit_inline(child, context=context, deferred_footnotes=deferred_footnotes)
            for child in children
        )

    def emit_inline(
        self,
        node: object,
        *,
        context: str = "normal",
        deferred_footnotes: list[str] | None = None,
    ) -> str:
        if isinstance(node, Text):
            return escape_latex(node.value)
        if isinstance(node, InlineExpression):
            return expression_value_to_lualatex(node.value, node.source, node.origin)
        if isinstance(node, Emphasis):
            return r"\emph{" + self.emit_inline_children(
                node.children,
                context=context,
                deferred_footnotes=deferred_footnotes,
            ) + "}"
        if isinstance(node, Strong):
            return r"\textbf{" + self.emit_inline_children(
                node.children,
                context=context,
                deferred_footnotes=deferred_footnotes,
            ) + "}"
        if isinstance(node, InlineCode):
            return r"\texttt{" + escape_plain_latex(node.value) + "}"
        if isinstance(node, Link):
            label = self.emit_inline_children(
                node.children,
                context=context,
                deferred_footnotes=deferred_footnotes,
            )
            return r"\href{" + escape_url(node.target) + "}{" + label + "}"
        if isinstance(node, Image):
            return r"\includegraphics{" + escape_url(node.target) + "}"
        if isinstance(node, FootnoteRef):
            return self.emit_footnote_ref(node, context, deferred_footnotes)
        if isinstance(node, Citation):
            return self.bibliography.cite(node, context, deferred_footnotes)
        raise MarkTeXError(f"unsupported inline node for LuaLaTeX backend: {node!r}")

    def emit_footnote_ref(
        self,
        node: FootnoteRef,
        context: str,
        deferred_footnotes: list[str] | None,
    ) -> str:
        footnote = self.footnotes.get(node.label)
        if footnote is None:
            raise MarkTeXError(f"undefined footnote: {node.label}", node.origin)
        text = self.emit_inline_children(footnote.children)
        if context == "table_cell":
            if deferred_footnotes is None:
                raise MarkTeXError("table footnote queue is unavailable", node.origin)
            deferred_footnotes.append(text)
            return r"\footnotemark"
        return r"\footnote{" + text + "}"

    def emit_conditional(self, block: Conditional) -> list[str]:
        selected = concrete_conditional_body(block)
        if selected is not None:
            lines: list[str] = []
            for child in selected:
                lines.extend(self.emit_block(child))
            return lines
        if len(block.branches) == 1 and not block.else_body:
            condition = block.branches[0].condition
            if page_current_equals_total(condition):
                lines = [r"\ifnum\value{page}=\getpagerefnumber{LastPage}"]
                for child in block.branches[0].body:
                    lines.extend(self.emit_block(child))
                lines.append(r"\fi")
                return lines
        raise MarkTeXError("unsupported symbolic conditional for LuaLaTeX MVP", block.origin)


def layout_options(document: Document) -> list[str]:
    options: list[str] = []
    for event in document.events:
        if isinstance(event, DocumentPatch) and event.call.head == "layout":
            for arg in event.call.args:
                if isinstance(arg, CallUnit):
                    paper = raw_kw(arg, "paper")
                    orientation = raw_kw(arg, "orientation")
                    if paper and paper not in options:
                        options.append(paper)
                    if orientation and orientation != "portrait" and orientation not in options:
                        options.append(orientation)
                elif isinstance(arg, RawString):
                    raw = arg.text.strip().lower()
                    if raw in {"a4", "a4paper"} and "a4paper" not in options:
                        options.append("a4paper")
                    elif raw == "landscape" and "landscape" not in options:
                        options.append("landscape")
    return options


def raw_kw(call: CallUnit, key: str) -> str | None:
    value = call.kwargs.get(key)
    if isinstance(value, RawString):
        return value.text
    return None


def escape_latex(text: str) -> str:
    return escape_plain_latex(text)


def escape_plain_latex(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def expression_value_to_lualatex(value: object, source: str, origin: SourceSpan | None = None) -> str:
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "CURRENT":
        return r"\thepage{}"
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "TOTAL":
        return r"\pageref{LastPage}"
    if isinstance(value, SymbolicExpr):
        raise MarkTeXError(f"unsupported symbolic expression for LuaLaTeX MVP: {source}", origin)
    return escape_latex(str(value))


def concrete_conditional_body(block: Conditional) -> tuple[object, ...] | None:
    for branch in block.branches:
        if isinstance(branch.condition, bool) and branch.condition:
            return branch.body
        if not isinstance(branch.condition, bool):
            return None
    return block.else_body if block.else_body else ()


def page_current_equals_total(condition: object) -> bool:
    if not isinstance(condition, SymbolicExpr) or condition.op != "eq":
        return False
    operands = condition.operands
    if len(operands) != 2:
        return False
    left, right = operands
    return (
        isinstance(left, SymbolicValue)
        and isinstance(right, SymbolicValue)
        and left.owner == "PAGE"
        and left.name == "CURRENT"
        and right.owner == "PAGE"
        and right.name == "TOTAL"
    )


def escape_url(text: str) -> str:
    return text.replace("\\", "/").replace("}", r"\}").replace("{", r"\{")
