from __future__ import annotations

from collections.abc import Mapping

from marktex.backend.lualatex.bibliography import LuaLaTeXBibliography, bibliography_snapshot
from marktex.core import (
    Block,
    BlockQuote,
    Citation,
    CodeBlock,
    CodeExpression,
    CodePart,
    CodeText,
    Conditional,
    Document,
    DocumentPatch,
    Emphasis,
    FootnoteDefinition,
    FootnoteRef,
    Heading,
    Image,
    InlineCode,
    InlineExpression,
    InlineMath,
    InlineNode,
    LineBreak,
    Link,
    ListBlock,
    ListItem,
    MathBlock,
    PageBreak,
    PageSetup,
    Paragraph,
    Strong,
    Strikethrough,
    Table,
    Text,
    ThematicBreak,
)
from marktex.core import object_to_json
from marktex.host.python.symbolic import SymbolicExpr, SymbolicValue
from marktex.mos import CallUnit, RawString
from marktex.semantics import MARGIN_KEYS, PageLayout, canonicalize_document
from marktex.source import MarkTeXError, SourceSpan


ENUMERATE_COUNTERS = ("enumi", "enumii", "enumiii", "enumiv")


def make_backend_ir(document: Document) -> dict[str, object]:
    return {
        "target": "lualatex",
        "document": object_to_json(document),
        "events": [object_to_json(event) for event in document.events],
        "blocks": [object_to_json(block) for block in document.blocks],
        "bibliography": bibliography_snapshot(document),
    }


def emit_lualatex(document: Document, *, bibliography: dict[str, object] | None = None) -> str:
    return LuaLaTeXEmitter(document, bibliography=bibliography).emit()


def emit_lualatex_from_backend_ir(backend_ir: dict[str, object]) -> str:
    from marktex.driver.serde import document_from_json

    target = backend_ir.get("target")
    if target != "lualatex":
        raise MarkTeXError(f"backend-ir target is {target!r}, not 'lualatex'")
    document = canonicalize_document(document_from_json(backend_ir.get("document")))
    bibliography = backend_ir.get("bibliography")
    if bibliography is not None and not isinstance(bibliography, dict):
        raise MarkTeXError("backend-ir bibliography snapshot is invalid")
    return emit_lualatex(document, bibliography=bibliography)


class LuaLaTeXEmitter:
    def __init__(
        self,
        document: Document,
        *,
        bibliography: dict[str, object] | None = None,
    ) -> None:
        self.document = document
        self.footnotes: Mapping[str, FootnoteDefinition] = {
            footnote.label: footnote for footnote in document.footnotes
        }
        self.bibliography = LuaLaTeXBibliography(
            document,
            escape_latex,
            escape_url,
            snapshot=bibliography,
        )

    def emit(self) -> str:
        geometry_options = layout_options(self.document)
        preamble = [
            "% Generated by MarkTeX 0.1. Target: lualatex.",
            r"\documentclass{article}",
            r"\usepackage{fontspec}",
            r"\usepackage{luatexja}",
            r"\usepackage{hyperref}",
            r"\usepackage{array}",
            r"\usepackage{lastpage}",
            r"\usepackage{graphicx}",
            r"\usepackage{refcount}",
        ]
        if document_uses_strikethrough(self.document):
            preamble.append(r"\usepackage[normalem]{ulem}")
        if geometry_options:
            preamble.append(r"\usepackage[" + ",".join(geometry_options) + r"]{geometry}")
        else:
            preamble.append(r"\usepackage{geometry}")
        preamble.extend(["", r"\begin{document}"])

        body: list[str] = []
        for block in self.document.blocks:
            body.extend(self.emit_block(block))
            body.append("")
        references = self.bibliography.reference_lines()
        if references:
            body.extend(references)
            body.append("")

        return "\n".join(preamble + body + [r"\end{document}", ""])

    def emit_block(self, block: Block, *, list_depth: int = 0) -> list[str]:
        if isinstance(block, Paragraph):
            return [self.emit_inline_children(block.children)]
        if isinstance(block, Heading):
            return [self.heading_command(block.level, block.children)]
        if isinstance(block, CodeBlock):
            return self.emit_code_block(block)
        if isinstance(block, MathBlock):
            return self.emit_math_block(block)
        if isinstance(block, Table):
            return self.emit_table(block)
        if isinstance(block, ListBlock):
            return self.emit_list(block, depth=list_depth)
        if isinstance(block, BlockQuote):
            return self.emit_blockquote(block, list_depth=list_depth)
        if isinstance(block, ThematicBreak):
            return [r"\par\noindent\rule{\linewidth}{0.4pt}\par"]
        if isinstance(block, PageBreak):
            return [r"\clearpage"]
        if isinstance(block, PageSetup):
            return emit_page_setup(block)
        if isinstance(block, Conditional):
            return self.emit_conditional(block, list_depth=list_depth)
        raise MarkTeXError(f"unsupported block for LuaLaTeX backend: {block!r}")

    def heading_command(self, level: int, children: tuple[InlineNode, ...]) -> str:
        command = {
            1: "section",
            2: "subsection",
            3: "subsubsection",
            4: "paragraph",
            5: "subparagraph",
            6: "subparagraph",
        }.get(level, "paragraph")
        return "\\" + command + "{" + self.emit_inline_children(children) + "}"

    def emit_code_block(self, block: CodeBlock) -> list[str]:
        lines = self.emit_code_lines(block)
        return [
            r"\par\begingroup\ttfamily",
            *(r"\noindent\strut " + line + r"\par" for line in lines),
            r"\endgroup",
        ]

    def emit_math_block(self, block: MathBlock) -> list[str]:
        body = block.body.rstrip("\n")
        if not body:
            return [r"\[", r"\]"]
        return [r"\[", *body.split("\n"), r"\]"]

    def emit_code_part(self, part: CodePart) -> str:
        if isinstance(part, CodeText):
            return escape_code_latex(part.value)
        if isinstance(part, CodeExpression):
            return expression_value_to_code_lualatex(part.value, part.source, part.origin)
        raise MarkTeXError(f"unsupported code part for LuaLaTeX backend: {part!r}")

    def emit_code_lines(self, block: CodeBlock) -> list[str]:
        if block.interpolated and block.parts:
            fragments = [self.emit_code_part(part) for part in block.parts]
        else:
            fragments = [escape_code_latex(block.body)]
        fragments = trim_trailing_newlines(fragments)
        lines = [""]
        for text in fragments:
            chunks = text.split("\n")
            for index, chunk in enumerate(chunks):
                if index:
                    lines.append("")
                lines[-1] += chunk
        return lines

    def emit_table(self, table: Table) -> list[str]:
        column_count = len(table.header)
        spec = "|".join(
            column_alignment(table.columns[index]) if index < len(table.columns) else "l"
            for index in range(column_count)
        )
        deferred_footnotes: list[str] = []
        lines = [r"\begin{tabular}{" + spec + "}"]
        lines.append(self.emit_table_row(table.header, deferred_footnotes))
        lines.append(r"\hline")
        for row in table.rows:
            lines.append(self.emit_table_row(row, deferred_footnotes))
        lines.append(r"\end{tabular}")
        if deferred_footnotes:
            lines.append(r"\addtocounter{footnote}{-" + str(len(deferred_footnotes)) + "}")
            lines.extend(
                r"\stepcounter{footnote}\footnotetext{" + footnote + "}"
                for footnote in deferred_footnotes
            )
        return lines

    def emit_table_row(
        self,
        row: tuple[tuple[InlineNode, ...], ...],
        deferred_footnotes: list[str],
    ) -> str:
        return (
            " & ".join(
                self.emit_inline_children(
                    cell,
                    context="table_cell",
                    deferred_footnotes=deferred_footnotes,
                )
                for cell in row
            )
            + r" \\"
        )

    def emit_list(self, block: ListBlock, *, depth: int) -> list[str]:
        if block.ordered and depth >= len(ENUMERATE_COUNTERS):
            raise MarkTeXError(
                "ordered list nesting deeper than LuaLaTeX backend supports",
                block.origin,
            )
        environment = "enumerate" if block.ordered else "itemize"
        lines = [r"\begin{" + environment + "}"]
        if block.ordered and block.start != 1:
            lines.append(
                r"\setcounter{"
                + ENUMERATE_COUNTERS[depth]
                + "}{"
                + str(block.start - 1)
                + "}"
            )
        for item in block.items:
            lines.extend(self.emit_list_item(item, list_depth=depth + 1))
        lines.append(r"\end{" + environment + "}")
        return lines

    def emit_list_item(self, item: ListItem, *, list_depth: int) -> list[str]:
        prefix = r"\item"
        if item.checked is True:
            prefix = r"\item[{[x]}]"
        elif item.checked is False:
            prefix = r"\item[{[ ]}]"
        if not item.children:
            return [prefix]
        first, *rest = item.children
        first_lines = self.emit_block(first, list_depth=list_depth)
        if first_lines:
            lines = [prefix + " " + first_lines[0]]
            lines.extend(first_lines[1:])
        else:
            lines = [prefix]
        for child in rest:
            lines.extend(self.emit_block(child, list_depth=list_depth))
        return lines

    def emit_blockquote(self, block: BlockQuote, *, list_depth: int) -> list[str]:
        lines = [r"\begin{quote}"]
        for child in block.children:
            lines.extend(self.emit_block(child, list_depth=list_depth))
        lines.append(r"\end{quote}")
        return lines

    def emit_inline_children(
        self,
        children: tuple[InlineNode, ...],
        *,
        context: str = "normal",
        deferred_footnotes: list[str] | None = None,
    ) -> str:
        return "".join(
            self.emit_inline(child, context=context, deferred_footnotes=deferred_footnotes)
            for child in children
        )

    def emit_inline(
        self,
        node: InlineNode,
        *,
        context: str = "normal",
        deferred_footnotes: list[str] | None = None,
    ) -> str:
        if isinstance(node, Text):
            return escape_latex(node.value)
        if isinstance(node, InlineExpression):
            return expression_value_to_lualatex(node.value, node.source, node.origin)
        if isinstance(node, Emphasis):
            return r"\emph{" + self.emit_inline_children(
                node.children,
                context=context,
                deferred_footnotes=deferred_footnotes,
            ) + "}"
        if isinstance(node, Strong):
            return r"\textbf{" + self.emit_inline_children(
                node.children,
                context=context,
                deferred_footnotes=deferred_footnotes,
            ) + "}"
        if isinstance(node, Strikethrough):
            return r"\sout{" + self.emit_inline_children(
                node.children,
                context=context,
                deferred_footnotes=deferred_footnotes,
            ) + "}"
        if isinstance(node, InlineCode):
            return r"\texttt{" + escape_plain_latex(node.value) + "}"
        if isinstance(node, InlineMath):
            return r"\(" + node.body + r"\)"
        if isinstance(node, LineBreak):
            return r"\\" if node.hard else " "
        if isinstance(node, Link):
            label = self.emit_inline_children(
                node.children,
                context=context,
                deferred_footnotes=deferred_footnotes,
            )
            return r"\href{" + escape_url(node.target) + "}{" + label + "}"
        if isinstance(node, Image):
            return r"\includegraphics{" + escape_url(node.target) + "}"
        if isinstance(node, FootnoteRef):
            return self.emit_footnote_ref(node, context, deferred_footnotes)
        if isinstance(node, Citation):
            return self.bibliography.cite(node, context, deferred_footnotes)
        raise MarkTeXError(f"unsupported inline node for LuaLaTeX backend: {node!r}")

    def emit_footnote_ref(
        self,
        node: FootnoteRef,
        context: str,
        deferred_footnotes: list[str] | None,
    ) -> str:
        footnote = self.footnotes.get(node.label)
        if footnote is None:
            raise MarkTeXError(f"undefined footnote: {node.label}", node.origin)
        text = self.emit_inline_children(footnote.children)
        if context == "table_cell":
            if deferred_footnotes is None:
                raise MarkTeXError("table footnote queue is unavailable", node.origin)
            deferred_footnotes.append(text)
            return r"\footnotemark"
        return r"\footnote{" + text + "}"

    def emit_conditional(self, block: Conditional, *, list_depth: int = 0) -> list[str]:
        selected = concrete_conditional_body(block)
        if selected is not None:
            lines: list[str] = []
            for child in selected:
                lines.extend(self.emit_block(child, list_depth=list_depth))
            return lines
        if len(block.branches) == 1 and not block.else_body:
            condition = block.branches[0].condition
            if page_current_equals_total(condition):
                lines = [r"\ifnum\value{page}=\getpagerefnumber{LastPage}"]
                for child in block.branches[0].body:
                    lines.extend(self.emit_block(child, list_depth=list_depth))
                lines.append(r"\fi")
                return lines
        raise MarkTeXError("unsupported symbolic conditional for LuaLaTeX backend", block.origin)


def layout_options(document: Document) -> list[str]:
    layout = PageLayout()
    touched = False
    for event in document.events:
        if isinstance(event, DocumentPatch) and event.call.head == "layout":
            width = raw_kw(event.call, "width")
            height = raw_kw(event.call, "height")
            if width is not None and height is not None:
                layout = layout.with_size(width, height)
                touched = True
            margins = {
                key: value
                for key in MARGIN_KEYS
                if (value := raw_kw(event.call, key)) is not None
            }
            if margins:
                layout = layout.with_margins(margins)
                touched = True
        elif isinstance(event, DocumentPatch) and event.call.head == "margin":
            margins = {
                key: value
                for key in MARGIN_KEYS
                if (value := raw_kw(event.call, key)) is not None
            }
            if margins:
                layout = layout.with_margins(margins)
                touched = True
    return geometry_options(layout) if touched else []


def geometry_options(layout: PageLayout) -> list[str]:
    options = [f"paperwidth={layout.width}", f"paperheight={layout.height}"]
    options.extend(f"{key}={value}" for key, value in layout.margin_dict().items())
    return options


def emit_page_setup(block: PageSetup) -> list[str]:
    layout = PageLayout(block.width, block.height, block.margins)
    return [r"\clearpage", r"\newgeometry{" + ",".join(geometry_options(layout)) + "}"]


def raw_kw(call: CallUnit, key: str) -> str | None:
    value = call.kwargs.get(key)
    if isinstance(value, RawString):
        return value.text
    return None


def column_alignment(call: CallUnit) -> str:
    align = raw_kw(call, "align")
    if align is None:
        return "l"
    normalized = align.strip().lower()
    if normalized not in {"left", "center", "right"}:
        raise MarkTeXError(f"unsupported table column alignment: {align}", call.origin)
    return {"left": "l", "center": "c", "right": "r"}[normalized]


def document_uses_strikethrough(document: Document) -> bool:
    return any(block_uses_strikethrough(block) for block in document.blocks) or any(
        inline_nodes_use_strikethrough(footnote.children) for footnote in document.footnotes
    )


def block_uses_strikethrough(block: Block) -> bool:
    if isinstance(block, Paragraph | Heading):
        return inline_nodes_use_strikethrough(block.children)
    if isinstance(block, Table):
        return any(
            inline_nodes_use_strikethrough(cell)
            for row in (block.header, *block.rows)
            for cell in row
        )
    if isinstance(block, ListBlock):
        return any(
            block_uses_strikethrough(child)
            for item in block.items
            for child in item.children
        )
    if isinstance(block, BlockQuote):
        return any(block_uses_strikethrough(child) for child in block.children)
    if isinstance(block, Conditional):
        return any(
            block_uses_strikethrough(child)
            for branch in block.branches
            for child in branch.body
        ) or any(block_uses_strikethrough(child) for child in block.else_body)
    return False


def inline_nodes_use_strikethrough(nodes: tuple[InlineNode, ...]) -> bool:
    for node in nodes:
        if isinstance(node, Strikethrough):
            return True
        if isinstance(node, Emphasis | Strong | Link) and inline_nodes_use_strikethrough(
            node.children
        ):
            return True
    return False


def escape_latex(text: str) -> str:
    return escape_plain_latex(text)


def escape_plain_latex(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def escape_code_latex(text: str) -> str:
    replacements = {
        " ": "\\ ",
        "\t": "\\ \\ \\ \\ ",
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def expression_value_to_lualatex(value: object, source: str, origin: SourceSpan | None = None) -> str:
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "CURRENT":
        return r"\thepage{}"
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "TOTAL":
        return r"\pageref{LastPage}"
    if isinstance(value, SymbolicExpr):
        raise MarkTeXError(f"unsupported symbolic expression for LuaLaTeX backend: {source}", origin)
    return escape_latex(str(value))


def expression_value_to_code_lualatex(
    value: object,
    source: str,
    origin: SourceSpan | None = None,
) -> str:
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "CURRENT":
        return r"\thepage{}"
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "TOTAL":
        return r"\pageref{LastPage}"
    if isinstance(value, SymbolicExpr):
        raise MarkTeXError(f"unsupported symbolic expression for LuaLaTeX backend: {source}", origin)
    return escape_code_latex(str(value))


def trim_trailing_newlines(fragments: list[str]) -> list[str]:
    result = list(fragments)
    while result:
        text = result[-1]
        trimmed = text.rstrip("\n")
        if trimmed == text:
            break
        if trimmed:
            result[-1] = trimmed
            break
        result.pop()
    return result or [""]


def concrete_conditional_body(block: Conditional) -> tuple[Block, ...] | None:
    for branch in block.branches:
        if isinstance(branch.condition, bool) and branch.condition:
            return branch.body
        if not isinstance(branch.condition, bool):
            return None
    return block.else_body if block.else_body else ()


def page_current_equals_total(condition: object) -> bool:
    if not isinstance(condition, SymbolicExpr) or condition.op != "eq":
        return False
    operands = condition.operands
    if len(operands) != 2:
        return False
    left, right = operands
    return (
        isinstance(left, SymbolicValue)
        and isinstance(right, SymbolicValue)
        and left.owner == "PAGE"
        and left.name == "CURRENT"
        and right.owner == "PAGE"
        and right.name == "TOTAL"
    )


def escape_url(text: str) -> str:
    return text.replace("\\", "/").replace("}", r"\}").replace("{", r"\{")
