from __future__ import annotations

from marktex.core import (
    Citation,
    CodeBlock,
    Conditional,
    Document,
    DocumentPatch,
    Emphasis,
    FootnoteRef,
    Heading,
    Image,
    InlineCode,
    InlineExpression,
    Link,
    Paragraph,
    Strong,
    Table,
    Text,
)
from marktex.core import object_to_json
from marktex.host.python.symbolic import SymbolicExpr, SymbolicValue
from marktex.mos import CallUnit, RawString
from marktex.source import MarkTeXError, SourceSpan


def make_backend_ir(document: Document) -> dict[str, object]:
    return {
        "target": "lualatex",
        "events": [object_to_json(event) for event in document.events],
        "blocks": [object_to_json(block) for block in document.blocks],
    }


def emit_lualatex(document: Document) -> str:
    geometry_options = layout_options(document)
    preamble = [
        "% Generated by MarkTeX V0. Target: lualatex.",
        r"\documentclass{article}",
        r"\usepackage{fontspec}",
        r"\usepackage{luatexja}",
        r"\usepackage{hyperref}",
        r"\usepackage{array}",
        r"\usepackage{lastpage}",
        r"\usepackage{graphicx}",
        r"\usepackage{refcount}",
    ]
    if geometry_options:
        preamble.append(r"\usepackage[" + ",".join(geometry_options) + r"]{geometry}")
    else:
        preamble.append(r"\usepackage{geometry}")
    preamble.extend(["", r"\begin{document}"])

    body: list[str] = []
    footnotes = {footnote.label: footnote for footnote in document.footnotes}
    for block in document.blocks:
        body.extend(block_to_lualatex(block, footnotes))
        body.append("")

    return "\n".join(preamble + body + [r"\end{document}", ""])


def block_to_lualatex(block: object, footnotes: dict[str, object]) -> list[str]:
    if isinstance(block, Paragraph):
        return ["".join(inline_to_lualatex(child, footnotes) for child in block.children)]
    if isinstance(block, Heading):
        return [heading_command(block.level, block.text)]
    if isinstance(block, CodeBlock):
        return [r"\begin{verbatim}", block.body.rstrip("\n"), r"\end{verbatim}"]
    if isinstance(block, Table):
        return table_to_latex(block)
    if isinstance(block, Conditional):
        return conditional_to_lualatex(block, footnotes)
    raise MarkTeXError(f"unsupported block for LuaLaTeX backend: {block!r}")


def layout_options(document: Document) -> list[str]:
    options: list[str] = []
    for event in document.events:
        if isinstance(event, DocumentPatch) and event.call.head == "layout":
            for arg in event.call.args:
                if isinstance(arg, CallUnit):
                    paper = raw_kw(arg, "paper")
                    orientation = raw_kw(arg, "orientation")
                    if paper and paper not in options:
                        options.append(paper)
                    if orientation and orientation != "portrait" and orientation not in options:
                        options.append(orientation)
                elif isinstance(arg, RawString):
                    raw = arg.text.strip().lower()
                    if raw in {"a4", "a4paper"} and "a4paper" not in options:
                        options.append("a4paper")
                    elif raw == "landscape" and "landscape" not in options:
                        options.append("landscape")
    return options


def raw_kw(call: CallUnit, key: str) -> str | None:
    value = call.kwargs.get(key)
    if isinstance(value, RawString):
        return value.text
    return None


def heading_command(level: int, text: str) -> str:
    command = {
        1: "section",
        2: "subsection",
        3: "subsubsection",
        4: "paragraph",
        5: "subparagraph",
        6: "subparagraph",
    }.get(level, "paragraph")
    return "\\" + command + "{" + escape_latex(text) + "}"


def table_to_latex(table: Table) -> list[str]:
    column_count = len(table.header)
    spec = "|".join(["l"] * column_count)
    lines = [r"\begin{tabular}{" + spec + "}"]
    lines.append(" & ".join(escape_latex(cell) for cell in table.header) + r" \\")
    lines.append(r"\hline")
    for row in table.rows:
        lines.append(" & ".join(escape_latex(cell) for cell in row) + r" \\")
    lines.append(r"\end{tabular}")
    return lines


def escape_latex(text: str) -> str:
    return escape_plain_latex(text)


def inline_to_lualatex(node: object, footnotes: dict[str, object] | None = None) -> str:
    footnotes = footnotes or {}
    if isinstance(node, Text):
        return escape_latex(node.value)
    if isinstance(node, InlineExpression):
        return expression_value_to_lualatex(node.value, node.source, node.origin)
    if isinstance(node, Emphasis):
        return r"\emph{" + "".join(inline_to_lualatex(child, footnotes) for child in node.children) + "}"
    if isinstance(node, Strong):
        return r"\textbf{" + "".join(inline_to_lualatex(child, footnotes) for child in node.children) + "}"
    if isinstance(node, InlineCode):
        return r"\texttt{" + escape_plain_latex(node.value) + "}"
    if isinstance(node, Link):
        label = "".join(inline_to_lualatex(child, footnotes) for child in node.children)
        return r"\href{" + escape_url(node.target) + "}{" + label + "}"
    if isinstance(node, Image):
        return r"\includegraphics{" + escape_url(node.target) + "}"
    if isinstance(node, FootnoteRef):
        footnote = footnotes.get(node.label)
        if footnote is None:
            raise MarkTeXError(f"undefined footnote: {node.label}", node.origin)
        children = getattr(footnote, "children")
        return r"\footnote{" + "".join(inline_to_lualatex(child, footnotes) for child in children) + "}"
    if isinstance(node, Citation):
        key_text = ", ".join(node.keys)
        if node.kwargs:
            suffix = "; " + ", ".join(f"{key}={value}" for key, value in node.kwargs.items())
        else:
            suffix = ""
        return r"\textsuperscript{[" + escape_latex(key_text + suffix) + "]}"
    raise MarkTeXError(f"unsupported inline node for LuaLaTeX backend: {node!r}")


def escape_plain_latex(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def expression_value_to_lualatex(value: object, source: str, origin: SourceSpan | None = None) -> str:
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "CURRENT":
        return r"\thepage{}"
    if isinstance(value, SymbolicValue) and value.owner == "PAGE" and value.name == "TOTAL":
        return r"\pageref{LastPage}"
    if isinstance(value, SymbolicExpr):
        raise MarkTeXError(f"unsupported symbolic expression for LuaLaTeX MVP: {source}", origin)
    return escape_latex(str(value))


def conditional_to_lualatex(block: Conditional, footnotes: dict[str, object]) -> list[str]:
    selected = concrete_conditional_body(block)
    if selected is not None:
        lines: list[str] = []
        for child in selected:
            lines.extend(block_to_lualatex(child, footnotes))
        return lines
    if len(block.branches) == 1 and not block.else_body:
        condition = block.branches[0].condition
        if page_current_equals_total(condition):
            lines = [r"\ifnum\value{page}=\getpagerefnumber{LastPage}"]
            for child in block.branches[0].body:
                lines.extend(block_to_lualatex(child, footnotes))
            lines.append(r"\fi")
            return lines
    raise MarkTeXError("unsupported symbolic conditional for LuaLaTeX MVP", block.origin)


def concrete_conditional_body(block: Conditional) -> tuple[object, ...] | None:
    for branch in block.branches:
        if isinstance(branch.condition, bool) and branch.condition:
            return branch.body
        if not isinstance(branch.condition, bool):
            return None
    return block.else_body if block.else_body else ()


def page_current_equals_total(condition: object) -> bool:
    if not isinstance(condition, SymbolicExpr) or condition.op != "eq":
        return False
    operands = condition.operands
    if len(operands) != 2:
        return False
    left, right = operands
    return (
        isinstance(left, SymbolicValue)
        and isinstance(right, SymbolicValue)
        and left.owner == "PAGE"
        and left.name == "CURRENT"
        and right.owner == "PAGE"
        and right.name == "TOTAL"
    )


def escape_url(text: str) -> str:
    return text.replace("\\", "/").replace("}", r"\}").replace("{", r"\{")
