from __future__ import annotations

import json


def emit_host_script(surface_artifact: dict[str, object], *, no_host: bool = False) -> str:
    payload = json.dumps(surface_artifact, ensure_ascii=False, sort_keys=True)
    return (
        "# Generated by MarkTeX 0.1.\n"
        "# This construction script is an executable compiler artifact.\n"
        "from __future__ import annotations\n"
        "\n"
        "import json\n"
        "import marktex.runtime as marktex\n"
        "\n"
        f"surface_artifact = json.loads({payload!r})\n"
        f"document = marktex.document_from_surface_artifact(surface_artifact, no_host={no_host!r})\n"
    )
