from __future__ import annotations

from marktex.core import Document, DocumentPatch, ScopeClose, ScopePush
from marktex.mos import CallUnit, RawString, TupleValue
from marktex.mos.model import MosValue


def emit_host_script(document: Document) -> str:
    lines = [
        "# Generated by MarkTeX V0.",
        "import marktex",
        "from marktex.runtime import document_patch, scope_push, scope_close",
        "",
    ]
    for event in document.events:
        if isinstance(event, DocumentPatch):
            lines.append(f"marktex.invoke({call_to_runtime(event.call)})")
        elif isinstance(event, ScopePush):
            lines.append(f"marktex.invoke({scope_push_to_runtime(event)})")
        elif isinstance(event, ScopeClose):
            lines.append(f"marktex.invoke(scope_close({event.key!r}))")
    if document.blocks:
        lines.append("")
    for block in document.blocks:
        lines.append(f"# block: {block.__class__.__name__}")
    lines.append("")
    lines.append("document = marktex.finish()")
    return "\n".join(lines) + "\n"


def call_to_runtime(call: CallUnit) -> str:
    args = ", ".join(value_to_runtime(arg) for arg in call.args)
    kwargs = ", ".join(f"{key}={value_to_runtime(value)}" for key, value in call.kwargs.items())
    pieces = [repr(call.head)]
    if args:
        pieces.append(args)
    if kwargs:
        pieces.append(kwargs)
    return f"document_patch({', '.join(pieces)})"


def scope_push_to_runtime(scope: ScopePush) -> str:
    args = ", ".join(value_to_runtime(arg) for arg in scope.args)
    kwargs = ", ".join(f"{key}={value_to_runtime(value)}" for key, value in scope.kwargs.items())
    pieces = [repr(scope.key)]
    if args:
        pieces.append(args)
    pieces.append('scope="DEFAULT"')
    if kwargs:
        pieces.append(kwargs)
    return f"scope_push({', '.join(pieces)})"


def value_to_runtime(value: object) -> str:
    if isinstance(value, RawString):
        return repr(value.text)
    if isinstance(value, TupleValue):
        return "(" + ", ".join(value_to_runtime(item) for item in value.items) + ")"
    if isinstance(value, CallUnit):
        return call_to_runtime(value)
    return repr(value)
