from __future__ import annotations

from marktex.core import Document, DocumentPatch, ScopeClose, ScopePush
from marktex.mos import CallUnit, RawString, TupleValue


def emit_host_script(document: Document) -> str:
    lines = [
        "# Generated by MarkTeX V0.",
        "import marktex.runtime as marktex",
        "",
        "marktex.reset()",
    ]
    for event in document.events:
        if isinstance(event, DocumentPatch):
            lines.append(f"marktex.invoke({document_patch_to_runtime(event.call)})")
        elif isinstance(event, ScopePush):
            lines.append(f"marktex.invoke({scope_push_to_runtime(event)})")
        elif isinstance(event, ScopeClose):
            lines.append(f"marktex.invoke(marktex.scope_close({event.key!r}))")
    if document.blocks:
        lines.append("")
    for block in document.blocks:
        lines.append(f"# block: {block.__class__.__name__}")
    lines.append("")
    lines.append("document = marktex.finish()")
    return "\n".join(lines) + "\n"


def call_to_runtime(call: CallUnit) -> str:
    return f"marktex.call({call_arguments(call, include_context=True)})"


def document_patch_to_runtime(call: CallUnit) -> str:
    return f"marktex.document_patch({call_arguments(call, include_context=False)})"


def call_arguments(call: CallUnit, *, include_context: bool) -> str:
    args = ", ".join(value_to_runtime(arg) for arg in call.args)
    kwargs = ", ".join(f"{key}={value_to_runtime(value)}" for key, value in call.kwargs.items())
    pieces = [repr(call.head)]
    if args:
        pieces.append(args)
    if include_context and call.context != "document":
        pieces.append(f"context={call.context!r}")
    if kwargs:
        pieces.append(kwargs)
    return ", ".join(pieces)


def scope_push_to_runtime(scope: ScopePush) -> str:
    args = ", ".join(value_to_runtime(arg) for arg in scope.args)
    kwargs = ", ".join(f"{key}={value_to_runtime(value)}" for key, value in scope.kwargs.items())
    pieces = [repr(scope.key)]
    if args:
        pieces.append(args)
    if kwargs:
        pieces.append(kwargs)
    return f"marktex.scope_push({', '.join(pieces)})"


def value_to_runtime(value: object) -> str:
    if isinstance(value, RawString):
        if value.force_raw:
            return f"marktex.raw({value.text!r}, force_raw=True)"
        return repr(value.text)
    if isinstance(value, TupleValue):
        return "marktex.tuple_value(" + ", ".join(value_to_runtime(item) for item in value.items) + ")"
    if isinstance(value, CallUnit):
        return call_to_runtime(value)
    return repr(value)
